# Generated by Django 5.2.1 on 2025-11-17 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReporteViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_viajes', models.IntegerField()),
                ('viajes_completados', models.IntegerField()),
                ('viajes_en_curso', models.IntegerField()),
                ('total_entregas', models.IntegerField()),
                ('entregas_exitosas', models.IntegerField()),
                ('entregas_fallidas', models.IntegerField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_por_racion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('direccion_entrega', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('cantidad_cajas', models.PositiveIntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_entrega_solicitada', models.DateField(blank=True, null=True)),
                ('instrucciones_especiales', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion_gmexpress.cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion_gmexpress.estadopedido')),
                ('tipo_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion_gmexpress.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('intentos_login', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_pedidos', to='gestion_gmexpress.estadopedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='gestion_gmexpress.pedido')),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_pedido', to='gestion_gmexpress.perfilusuario')),
            ],
            options={
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('tipo_licencia', models.CharField(max_length=20)),
                ('vencimiento_licencia', models.DateField()),
                ('experiencia_meses', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to='gestion_gmexpress.perfilusuario')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='gestion_gmexpress.perfilusuario'),
        ),
        migrations.CreateModel(
            name='AuditoriaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ASIGNAR', 'Asignar'), ('REMOVER', 'Remover')], max_length=10)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_ejecutadas', to='gestion_gmexpress.perfilusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_roles', to='gestion_gmexpress.perfilusuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_roles', to='gestion_gmexpress.rol')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_asignados_por', to='gestion_gmexpress.perfilusuario')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='gestion_gmexpress.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_usuario', to='gestion_gmexpress.perfilusuario')),
            ],
            options={
                'unique_together': {('usuario', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='gestion_gmexpress.UsuarioRol', through_fields=('usuario', 'rol'), to='gestion_gmexpress.rol'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveSmallIntegerField()),
                ('capacidad_cajas', models.IntegerField()),
                ('kilometraje_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_asignacion_conductor', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_asignados', to='gestion_gmexpress.conductor')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='gestion_gmexpress.estadovehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=100)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('fecha_programada', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_salida_real', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada_estimada', models.TimeField(blank=True, null=True)),
                ('hora_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('cantidad_cajas_total', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='gestion_gmexpress.conductor')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_creados', to='gestion_gmexpress.perfilusuario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='gestion_gmexpress.estadoviaje')),
                ('tipo_ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='gestion_gmexpress.tiporuta')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='gestion_gmexpress.vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='gestion_gmexpress.viaje'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('SISTEMA', 'Sistema')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='gestion_gmexpress.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='gestion_gmexpress.perfilusuario')),
                ('viaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='gestion_gmexpress.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('hora_llegada_estimada', models.TimeField(blank=True, null=True)),
                ('hora_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('motivo_fallo', models.CharField(blank=True, choices=[('CLIENTE_AUSENTE', 'Cliente ausente'), ('DIRECCION_INCORRECTA', 'Dirección incorrecta'), ('CLIENTE_RECHAZO', 'Cliente rechazó'), ('ACCESO_BLOQUEADO', 'Acceso bloqueado'), ('OTRO', 'Otro')], max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_atendidas', to='gestion_gmexpress.conductor')),
                ('estado_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='gestion_gmexpress.estadoentrega')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='gestion_gmexpress.pedido')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='gestion_gmexpress.viaje')),
            ],
            options={
                'ordering': ['secuencia'],
                'unique_together': {('viaje', 'pedido'), ('viaje', 'secuencia')},
            },
        ),
    ]
